### ISSUE TITLE
Update for 1.7.3

### ISSUE THREAD

**Issue by Monniasza** [StupidChris/RealChute#84]
RealChute doesn't work with 1.7.3 and doesn't fix Ferram Aerospace Research breaking all parachutes.

**Comment by Starwaster** [comment]
The latest build of RealChute most definitely works with 1.7.3. I know that for a fact. 

As for the second half of your sentence however; it is inappropriately shifting responsibility onto RealChute for a third party mod breaking RealChute _when that mod itself (FAR) has had no official updates since KSP 1.3.1?_

Do you really not see something wrong with that?
